on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
        # Navigate to the project directory
        cd /var/www/onu2024
        # Ensure the repository is up to date
        git pull
        # Install 'n' to manage Node versions
        npm install -g n
        # Install and use Node v18.13
        n 18.13
        # Ensure the Node version is correctly updated in the session
        export N_PREFIX="$HOME/n"
        export PATH="$N_PREFIX/bin:$PATH"
        # Check Node.js version
        node -v
        # Condition to check if the Node version is as expected
        if [[ $(node -v) != v18.13.* ]]; then
          echo "Node version not updated correctly."
          exit 1
        fi
        # Install dependencies and build the project
        npm install
        npm run build --prod
        # Copy build artifacts to the NGINX serving directory
        sudo cp -r dist/* /var/www/html/
        # Set the correct permissions
        sudo chown -R www-data:www-data /var/www/html/
        # Optionally restart NGINX, if needed (usually not required for static content)
        sudo systemctl reload nginx
        EOF
