on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} <<EOF
        cd /var/www/onu2024
        git pull
        export N_PREFIX="$HOME/n"
        export PATH="$N_PREFIX/bin:$PATH"
        npm install -g n
        n 18.13
        PATH="$N_PREFIX/bin:$PATH" # Ensure updated PATH is used
        node -v  # Confirm Node version
        if [ $(node -v) != 'v18.13.*' ]; then
          echo "Node version not updated correctly."
          exit 1
        fi
        npm install
        npm run build
        pm2 delete app || true  # Ignore error if app does not exist
        pm2 serve dist/ --
