on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "cd /var/www/onu2024 && git pull && sudo chown -R $(whoami) /usr/local/ && export N_PREFIX=\"$HOME/n\" && export PATH=\"$N_PREFIX/bin:$PATH\" && npm install -g n && n latest && npm install && npm run build && pm2 delete app && pm2 serve dist/ --name app --spa"
